/*
 * СберСпасибо | Призолов
 *
 * Все формы передаются в формате multipart/form-data, ответы от сервера приходят в виде json.
 *
 * OpenAPI spec version: 1-oas3
 * Contact: sajvv@hismith.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Массив с ошибками валидации
    /// </summary>
    [DataContract]
    public partial class ValidationErrorErrors : IEquatable<ValidationErrorErrors>
    { 
        /// <summary>
        /// Название поля (name)
        /// </summary>
        /// <value>Название поля (name)</value>
        [DataMember(Name="FIELD_NAME")]
        public List<string> FIELD_NAME { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ValidationErrorErrors {\n");
            sb.Append("  FIELD_NAME: ").Append(FIELD_NAME).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ValidationErrorErrors)obj);
        }

        /// <summary>
        /// Returns true if ValidationErrorErrors instances are equal
        /// </summary>
        /// <param name="other">Instance of ValidationErrorErrors to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ValidationErrorErrors other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    FIELD_NAME == other.FIELD_NAME ||
                    FIELD_NAME != null &&
                    FIELD_NAME.SequenceEqual(other.FIELD_NAME)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (FIELD_NAME != null)
                    hashCode = hashCode * 59 + FIELD_NAME.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ValidationErrorErrors left, ValidationErrorErrors right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ValidationErrorErrors left, ValidationErrorErrors right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
