openapi: 3.0.0
info:
  title: 'СберСпасибо | Призолов'
  description: 'Все формы передаются в формате multipart/form-data, ответы от сервера приходят в виде json.'
  contact:
    email: sajvv@hismith.ru
  version: 1.0.0
paths:
  /game/demo/remove:
    post:
      tags:
        - Игра
      summary: 'Снятие демо режима'
      description: 'Снямает демо режим с пользователя. Без параметров.'
      operationId: 'App\Controller\Game\GameController::removeDemo'
      responses:
        '200':
          description: 'Успешное снятие. Ответа нет, код 200.'
  /game/user/info:
    post:
      tags:
        - Игра
      summary: 'Информация о текущем пользователе'
      description: 'Отображает список доступных локаций, ходов и демо режим'
      operationId: 'App\Controller\Game\GameController::userInfo'
      responses:
        '200':
          description: 'Информация о текущем пользователе'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
  /game/location/info:
    post:
      tags:
        - Игра
      summary: 'Информация о локации для пользователя'
      description: 'Информация о локации для пользователя'
      operationId: 'App\Controller\Game\LocationController::info'
      responses:
        '200':
          description: 'Информация о локации для пользователя'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationInfo'
  /register:
    post:
      tags:
        - 'Авторизация / Регистрация'
      summary: 'Регистрация нового пользователя'
      description: 'Регистрация пользователя'
      operationId: 'App\Controller\RegistrationController::register'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              required:
                - birthdate
                - phone
              properties:
                birthdate:
                  description: 'Дата рождения, формат dd-mm-YYYY'
                  type: string
                phone:
                  description: 'Телефон, 10 символов'
                  type: string
              type: object
      responses:
        '400':
          description: 'Есть ошибки валидации'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '500':
          description: 'Ошибка при сохранении, данные не сохранены'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BackendError'
        '200':
          description: 'Успешно сохранено. Ответа нет, код 200.'
  /auth:
    post:
      tags:
        - 'Авторизация / Регистрация'
      summary: 'Авторизация по email'
      description: 'Авторизация пользователя'
      operationId: 'App\Controller\SecurityController::auth'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              required:
                - email
              properties:
                email:
                  description: email
                  type: string
              type: object
      responses:
        '404':
          description: 'Пользователь не найден'
        '200':
          description: 'Успешный вход. Ответа нет, код 200.'
components:
  schemas:
    ValidationError:
      required:
        - error
        - errors
      properties:
        error:
          type: boolean
        errors:
          description: 'Массив с ошибками валидации'
          properties:
            FIELD_NAME:
              description: 'Название поля (name)'
              type: array
              items:
                description: 'Текст ошибки'
                type: string
          type: object
      type: object
    BackendError:
      required:
        - error
        - message
        - code
      properties:
        error:
          type: boolean
        message:
          description: 'Текст ошибки'
          type: string
        code:
          description: 'Код исключения'
          type: integer
      type: object
    UserInfo:
      required:
        - id
        - shots_available
        - isDemo
        - locations
      properties:
        id:
          description: 'ID текущего пользователя'
          type: integer
        shots_available:
          description: 'Количество доступных ходов'
          type: integer
        isDemo:
          description: 'Флаг демо пользователя'
          type: boolean
        locations:
          description: 'Массив с ошибками валидации'
          properties:
            LOCATION_ID:
              description: 'ИД локации'
              type: array
              items:
                description: 'Доступность локации'
                type: boolean
          type: object
      type: object
    LocationInfo:
      required:
        - id
        - shots_available
        - isDemo
        - locations
      properties:
        info:
          description: 'Информация о локации'
          properties:
            index:
              description: 'ID локации'
              type: string
            titles:
              description: 'Название локации'
              type: string
            cells:
              description: 'Количество клеток в локации'
              type: string
          type: object
        completed:
          description: 'Флаг пройденности локации'
          type: boolean
        shots:
          description: 'Массив с ошибками валидации'
          type: array
          items:
            properties:
              shots:
                description: 'Массив с ошибками валидации'
                properties:
                  index: { description: 'ID локации', type: string }
                  titles: { description: 'Название локации', type: string }
                  cells: { description: 'Количество клеток в локации', type: string }
                type: object
            type: object
      type: object
    Prize:
      title: Приз
      required:
        - title
      properties:
        id:
          description: ID
          type: integer
        title:
          description: Название
          type: string
      type: object
    PrizeGroup:
      title: 'Группы призов'
      required:
        - name
        - title
      properties:
        id:
          description: ID
          type: integer
        title:
          description: Название
          type: string
        name:
          description: 'Внутреннее наименование'
          type: string
      type: object
    PrizeType:
      title: 'Типы призов'
      required:
        - name
        - title
      properties:
        id:
          description: ID
          type: integer
        title:
          description: Название
          type: string
      type: object
    Task:
      title: Задание
      required:
        - title
        - openTopic
        - openMessage
        - closeTopic
        - closeMessage
        - prize
        - position
      properties:
        id:
          description: ID
          type: integer
        title:
          description: 'Краткое название'
          type: string
        openTopic:
          description: 'Полный заголовок'
          type: string
        openMessage:
          description: Описание
          type: string
        closeTopic:
          description: 'Заголовок при закрытии'
          type: string
        closeMessage:
          description: 'Описание при закрытии'
          type: string
        position:
          description: Сортировка
          type: integer
        prize:
          description: 'Приз за выполнение (id)'
          type: integer
        image:
          description: Изображение
          properties:
            name:
              description: 'название файла'
              type: string
            path:
              description: 'путь до файла'
              type: string
          type: object
      type: object
    User:
      title: Пользователь
      required:
        - email
        - title
        - account
        - attempts
        - blockDate
        - isRegistered
        - isEnabled
        - roles
      properties:
        id:
          description: ID
          type: integer
        email:
          description: Email
          type: string
        roles:
          description: 'Массив с названием ролей'
          type: array
          items:
            type: string
        password:
          description: 'Пароль (захэшированный)'
          type: string
        title:
          description: Название
          type: string
        accessCode:
          description: 'Код доступа'
          type: string
        attempts:
          description: 'Попытки входа'
          type: integer
        blockDate:
          description: 'Дата блокировки'
          type: string
          format: date-time
        isRegistered:
          description: 'Полностью зарегистрирован'
          type: boolean
        isEnabled:
          description: Доступность
          type: boolean
        account:
          description: 'Аккаунт (сущность Account)'
          type: integer
      type: object
    UserDataLog:
      title: 'Аккаунтский лог'
      required:
        - id
        - dateCreated
        - type
        - user
        - userIp
        - oldData
        - newData
      properties:
        id:
          description: ID
          type: integer
        dateCreated:
          description: 'Дата и время события'
          type: string
          format: date-time
        type:
          description: Тип
          type: string
          enum:
            - created
            - updated
        userIp:
          description: 'IP пользователя'
          type: string
        oldData:
          description: 'Изначальные данные'
          type: array
          items:
            description: 'любой формат json'
        newData:
          description: 'Новые данные'
          type: array
          items:
            description: 'любой формат json'
      type: object
    UserTask:
      title: 'Пользовательские задания'
      required:
        - id
        - task
        - account
        - dateCreated
        - dateStart
        - dateFinish
        - newData
        - isViewed
        - isCompleted
      properties:
        id:
          description: ID
          type: integer
        task:
          description: 'Задание (сущность Task)'
          type: integer
        account:
          description: 'Аккаунт (сущность Account)'
          type: integer
        dateCreated:
          description: 'Дата и время создания'
          type: string
          format: date-time
        dateCompleted:
          description: 'Дата и время выполнения'
          type: string
          format: date-time
        dateStart:
          description: 'Дата начала задания'
          type: string
          format: date-time
        dateFinish:
          description: 'Дата окончания задания'
          type: string
          format: date-time
        isViewed:
          description: Просмотрено
          type: boolean
        isCompleted:
          description: Выполнено
          type: boolean
      type: object
